/*
 * Shared between both Workers. Keep in sync with src/data/targets.ts.
 *
 * Why duplicated: Workers + Pages have separate bundlers. We avoid a
 * shared monorepo package here for simplicity; the list is short and
 * regenerated by hand on rare changes. A future scripts/sync-targets.mjs
 * can codegen this from astro-shell's FAMILY_* registries.
 */
export interface Target {
  slug: string
  name: string
  url: string
  category: 'master' | 'app' | 'api'
}

export const TARGETS: Target[] = [
  { slug: 'master', name: 'oriz.in', url: 'https://oriz.in', category: 'master' },

  { slug: 'me', name: 'me.oriz.in', url: 'https://me.oriz.in', category: 'app' },
  { slug: 'blog', name: 'blog.oriz.in', url: 'https://blog.oriz.in', category: 'app' },
  { slug: 'books', name: 'books.oriz.in', url: 'https://books.oriz.in', category: 'app' },
  { slug: 'book-lore', name: 'book-lore.oriz.in', url: 'https://book-lore.oriz.in', category: 'app' },
  { slug: 'financial-cards', name: 'financial-cards.oriz.in', url: 'https://financial-cards.oriz.in', category: 'app' },
  { slug: 'journal', name: 'journal.oriz.in', url: 'https://journal.oriz.in', category: 'app' },
  { slug: 'post', name: 'post.oriz.in', url: 'https://post.oriz.in', category: 'app' },
  { slug: 'packages', name: 'packages.oriz.in', url: 'https://packages.oriz.in', category: 'app' },

  { slug: 'pdf', name: 'pdf.oriz.in', url: 'https://pdf.oriz.in', category: 'app' },
  { slug: 'image', name: 'image.oriz.in', url: 'https://image.oriz.in', category: 'app' },
  { slug: 'text', name: 'text.oriz.in', url: 'https://text.oriz.in', category: 'app' },
  { slug: 'qr', name: 'qr.oriz.in', url: 'https://qr.oriz.in', category: 'app' },
  { slug: 'finance', name: 'finance.oriz.in', url: 'https://finance.oriz.in', category: 'app' },
  { slug: 'dev', name: 'dev.oriz.in', url: 'https://dev.oriz.in', category: 'app' },
  { slug: 'convert', name: 'convert.oriz.in', url: 'https://convert.oriz.in', category: 'app' },
  { slug: 'data', name: 'data.oriz.in', url: 'https://data.oriz.in', category: 'app' },
  { slug: 'audio', name: 'audio.oriz.in', url: 'https://audio.oriz.in', category: 'app' },
  { slug: 'video', name: 'video.oriz.in', url: 'https://video.oriz.in', category: 'app' },

  { slug: 'currency-api', name: 'currency-api.oriz.in', url: 'https://currency-api.oriz.in', category: 'api' },
  { slug: 'mmi-api', name: 'mmi-api.oriz.in', url: 'https://mmi-api.oriz.in', category: 'api' },
  { slug: 'rates-api', name: 'rates-api.oriz.in', url: 'https://rates-api.oriz.in', category: 'api' },
  { slug: 'pin-api', name: 'pin-api.oriz.in', url: 'https://pin-api.oriz.in', category: 'api' },
  { slug: 'ifsc-api', name: 'ifsc-api.oriz.in', url: 'https://ifsc-api.oriz.in', category: 'api' },
]
